a=int(input("Enter the integer number:"))
b=float(input("Enter the Float number:"))
c=input("Enter a word:")
d=bool(input("Enter the complex number:"))
print(a,'=',type(a),'type','And its id is=',id(a))
print(b,'=',type(b),'type','And its id is=',id(b))
print(c,'=',type(c),'type','And its id is=',id(c))
print(d,'=',type(d),'type','And its id is=',id(d))
